### ISSUE TITLE
Potential improvement for README?

### ISSUE THREAD

**Issue by Unparalleled-Calvin** [g1331/xiaomai-bot#19]
It seems that the tutorial for docker uses "-v" option where the former path should be an absolute path on the host machine. Here you use /xiaomai-bot/... but users may not clone the repo into the root path. Maybe `$(pwd)` is a better choice.

Additionally you can tag certain commits for release so that we can checkout to those stable versions easily.

**Comment by gili-gili** [comment]
Coming s∞n

**Comment by Ra2-IFV** [comment]
Check [this](https://docs.ifvlab.com/projects/xiaomai/zh_CN/latest/] as preview
