### ISSUE TITLE
关于gateway_api中不能运作的异步方法的解决办法

### ISSUE THREAD

**Issue by half-ghost** [g1331/xiaomai-bot#30]
佬你好，最近在抄你的gateway_api时，我想把所有网络请求都交给同个函数来处理，用到的也是aiohttp，然后在`Authentication_getEnvIdViaAuthCode`这个函数里也遇到了无法完成请求的情况，用postman测试后发现只要把该函数的header里的`Content-Length`项去掉即可正常发送请求，希望能帮到你。

**Comment by g1331** [comment]
忘了这个历史遗留问题了，大部分的HTTP库（包括aiohttp和requests）会自动计算并设置这个值。如果手动设置的"Content-Length"值和实际的请求体长度不一致，可能会导致服务器解析请求出错。早期屎山调试时并没有注意这个问题所以一直存到了现在(

**Comment by half-ghost** [comment]
草，还以为没发现这个原因，issue我先关了（
